# Generated by Django 5.0.6 on 2024-06-14 06:16

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today())),
            ],
        ),
    ]
