# Generated by Django 5.0.6 on 2024-06-14 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timestamp', '0003_work_day_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_day',
            name='date',
        ),
        migrations.AddField(
            model_name='work_day',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 15, 41, 48, 587367)),
        ),
        migrations.AddField(
            model_name='work_day',
            name='startime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 15, 41, 48, 587367)),
        ),
    ]
