# Generated by Django 5.0.6 on 2024-06-14 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timestamp', '0004_remove_work_day_date_work_day_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_day',
            name='time',
        ),
        migrations.AddField(
            model_name='work_day',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='work_day',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 15, 47, 46, 899181)),
        ),
        migrations.AlterField(
            model_name='work_day',
            name='startime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 15, 47, 46, 899181)),
        ),
    ]
