# Generated by Django 5.0.6 on 2024-06-14 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timestamp', '0005_remove_work_day_time_work_day_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_day',
            name='endtime',
            field=models.TimeField(default=datetime.datetime(2024, 6, 14, 16, 1, 7, 230657)),
        ),
        migrations.AlterField(
            model_name='work_day',
            name='startime',
            field=models.TimeField(default=datetime.time(1, 4)),
        ),
    ]
