# Generated by Django 5.0.6 on 2024-06-18 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timestamp', '0006_alter_work_day_endtime_alter_work_day_startime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_day',
            name='endtime',
            field=models.TimeField(default=datetime.time(1, 2, 3)),
        ),
    ]
