# Generated by Django 5.0.6 on 2024-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timestamp', '0007_alter_work_day_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_day',
            name='difference',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='work_day',
            name='seconds',
            field=models.TextField(default=''),
        ),
    ]
