# Generated by Django 5.0.6 on 2024-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timestamp', '0008_work_day_difference_work_day_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_day',
            name='difference',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='work_day',
            name='seconds',
            field=models.FloatField(default=0),
        ),
    ]
